#!/usr/bin/env python3
"""Build wiki/index.md deterministically from Markdown page frontmatter."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from wiki_common import (
    atomic_write_text,
    page_description,
    page_title,
    parse_frontmatter,
    today,
    wiki_markdown_files,
)


TYPE_ORDER = [
    "overview",
    "moc",
    "concept",
    "component",
    "decision",
    "guide",
    "source-note",
    "question",
]
TYPE_TITLES = {
    "overview": "Overviews",
    "moc": "Maps of content",
    "concept": "Concepts",
    "component": "Components",
    "decision": "Decisions",
    "guide": "Guides",
    "source-note": "Source notes",
    "question": "Open questions",
}


def render(root: Path) -> str:
    groups: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    page_dates: list[str] = []
    wiki_root = root / "wiki"
    for path in wiki_markdown_files(root):
        if path == wiki_root / "index.md":
            continue
        metadata, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        page_type = str(metadata.get("type") or "unclassified")
        updated = metadata.get("updated")
        if isinstance(updated, str) and updated:
            page_dates.append(updated)
        target = path.relative_to(wiki_root).with_suffix("").as_posix()
        title = page_title(body, path.stem)
        description = page_description(metadata, body)
        groups[page_type].append((target, title, description))

    lines = [
        "---",
        "id: wiki-index",
        "type: moc",
        "status: canonical",
        "sources: []",
        f"updated: {max(page_dates) if page_dates else today()}",
        "description: Generated catalog of every page in the LLM Wiki",
        "---",
        "",
        "# Wiki Index",
        "",
        "<!-- Generated by build_index.py. Edit page metadata, not this list. -->",
        "",
        "Start with [[overview|Overview]], then follow the smallest relevant set of links.",
        "",
    ]
    ordered_types = TYPE_ORDER + sorted(set(groups) - set(TYPE_ORDER))
    for page_type in ordered_types:
        pages = groups.get(page_type)
        if not pages:
            continue
        lines.extend([f"## {TYPE_TITLES.get(page_type, page_type.title())}", ""])
        for target, title, description in sorted(pages, key=lambda item: (item[1].lower(), item[0])):
            lines.append(f"- [[{target}|{title}]] — {description}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="knowledge")
    parser.add_argument("--check", action="store_true", help="Fail when index.md is stale")
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    if not (root / "wiki").exists():
        raise SystemExit(f"not an initialized LLM Wiki: {root}")
    index = root / "wiki" / "index.md"
    expected = render(root)
    if args.check:
        current = index.read_text(encoding="utf-8") if index.exists() else ""
        if current != expected:
            print(f"stale index: {index}")
            return 1
        print(f"index is current: {index}")
        return 0
    atomic_write_text(index, expected)
    print(f"built index: {index}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
